# Generated by Django 5.0.6 on 2024-12-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_asistencia_usuario_alter_asignatura_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='estado',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='contador',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
